<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.classifiers.trees.LMT" name="__root__" version="3.9.6">
   <object class="boolean" name="debug" primitive="yes">false</object>
   <object array="yes" class="java.lang.String" name="options">
      <object class="java.lang.String" name="0">-I</object>
      <object class="java.lang.String" name="1">-1</object>
      <object class="java.lang.String" name="2">-M</object>
      <object class="java.lang.String" name="3">15</object>
      <object class="java.lang.String" name="4">-W</object>
      <object class="java.lang.String" name="5">0.0</object>
   </object>
</object>
