<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.trees.RandomTree" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.RandomTree</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">0</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">1.0</object>
            <object class="java.lang.String" name="11">-V</object>
            <object class="java.lang.String" name="12">0.001</object>
            <object class="java.lang.String" name="13">-S</object>
            <object class="java.lang.String" name="14">1</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">10</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">0.25</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">2</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">20</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-P</object>
            <object class="java.lang.String" name="8">100</object>
            <object class="java.lang.String" name="9">-I</object>
            <object class="java.lang.String" name="10">100</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-K</object>
            <object class="java.lang.String" name="14">0</object>
            <object class="java.lang.String" name="15">-M</object>
            <object class="java.lang.String" name="16">1.0</object>
            <object class="java.lang.String" name="17">-V</object>
            <object class="java.lang.String" name="18">0.001</object>
            <object class="java.lang.String" name="19">-S</object>
            <object class="java.lang.String" name="20">1</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.MultilayerPerceptron" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-L</object>
            <object class="java.lang.String" name="1">0.3</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">0.2</object>
            <object class="java.lang.String" name="4">-N</object>
            <object class="java.lang.String" name="5">500</object>
            <object class="java.lang.String" name="6">-V</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-S</object>
            <object class="java.lang.String" name="9">0</object>
            <object class="java.lang.String" name="10">-E</object>
            <object class="java.lang.String" name="11">20</object>
            <object class="java.lang.String" name="12">-H</object>
            <object class="java.lang.String" name="13">a</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.MultilayerPerceptron</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-L</object>
            <object class="java.lang.String" name="8">0.3</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">0.2</object>
            <object class="java.lang.String" name="11">-N</object>
            <object class="java.lang.String" name="12">500</object>
            <object class="java.lang.String" name="13">-V</object>
            <object class="java.lang.String" name="14">0</object>
            <object class="java.lang.String" name="15">-S</object>
            <object class="java.lang.String" name="16">0</object>
            <object class="java.lang.String" name="17">-E</object>
            <object class="java.lang.String" name="18">20</object>
            <object class="java.lang.String" name="19">-H</object>
            <object class="java.lang.String" name="20">a</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.LMT" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">-1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="9">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.LMT</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-I</object>
            <object class="java.lang.String" name="8">-1</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">15</object>
            <object class="java.lang.String" name="11">-W</object>
            <object class="java.lang.String" name="12">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.rules.JRip" name="10">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">3</object>
            <object class="java.lang.String" name="2">-N</object>
            <object class="java.lang.String" name="3">2.0</object>
            <object class="java.lang.String" name="4">-O</object>
            <object class="java.lang.String" name="5">2</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="11">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.rules.JRip</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-F</object>
            <object class="java.lang.String" name="8">3</object>
            <object class="java.lang.String" name="9">-N</object>
            <object class="java.lang.String" name="10">2.0</object>
            <object class="java.lang.String" name="11">-O</object>
            <object class="java.lang.String" name="12">2</object>
            <object class="java.lang.String" name="13">-S</object>
            <object class="java.lang.String" name="14">1</object>
         </object>
      </object>
      <object class="weka.classifiers.rules.OneR" name="12">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-B</object>
            <object class="java.lang.String" name="1">6</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="13">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.rules.OneR</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-B</object>
            <object class="java.lang.String" name="8">6</object>
         </object>
      </object>
      <object class="weka.classifiers.rules.DecisionTable" name="14">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-X</object>
            <object class="java.lang.String" name="1">1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.BestFirst -D 1 -N 5</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="15">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.rules.DecisionTable</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-X</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">weka.attributeSelection.BestFirst -D 1 -N 5</object>
         </object>
      </object>
      <object class="weka.classifiers.lazy.IBk" name="16">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">1</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">0</object>
            <object class="java.lang.String" name="4">-A</object>
            <object class="java.lang.String" name="5">weka.core.neighboursearch.LinearNNSearch -A &quot;weka.core.EuclideanDistance -R first-last&quot;</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="17">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.lazy.IBk</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">0</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">weka.core.neighboursearch.LinearNNSearch -A &quot;weka.core.EuclideanDistance -R first-last&quot;</object>
         </object>
      </object>
      <object class="weka.classifiers.lazy.KStar" name="18">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-B</object>
            <object class="java.lang.String" name="1">40</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">a</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="19">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.lazy.KStar</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-B</object>
            <object class="java.lang.String" name="8">40</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">a</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SMO" name="20">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">1.0</object>
            <object class="java.lang.String" name="2">-L</object>
            <object class="java.lang.String" name="3">0.001</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1.0E-12</object>
            <object class="java.lang.String" name="6">-N</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-V</object>
            <object class="java.lang.String" name="9">-1</object>
            <object class="java.lang.String" name="10">-W</object>
            <object class="java.lang.String" name="11">1</object>
            <object class="java.lang.String" name="12">-K</object>
            <object class="java.lang.String" name="13">weka.classifiers.functions.supportVector.PolyKernel -E 1.0 -C 250007</object>
            <object class="java.lang.String" name="14">-calibrator</object>
            <object class="java.lang.String" name="15">weka.classifiers.functions.Logistic -R 1.0E-8 -M -1 -num-decimal-places 4</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="21">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.SMO</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">1.0</object>
            <object class="java.lang.String" name="9">-L</object>
            <object class="java.lang.String" name="10">0.001</object>
            <object class="java.lang.String" name="11">-P</object>
            <object class="java.lang.String" name="12">1.0E-12</object>
            <object class="java.lang.String" name="13">-N</object>
            <object class="java.lang.String" name="14">0</object>
            <object class="java.lang.String" name="15">-V</object>
            <object class="java.lang.String" name="16">-1</object>
            <object class="java.lang.String" name="17">-W</object>
            <object class="java.lang.String" name="18">1</object>
            <object class="java.lang.String" name="19">-K</object>
            <object class="java.lang.String" name="20">weka.classifiers.functions.supportVector.PolyKernel -E 1.0 -C 250007</object>
            <object class="java.lang.String" name="21">-calibrator</object>
            <object class="java.lang.String" name="22">weka.classifiers.functions.Logistic -R 1.0E-8 -M -1 -num-decimal-places 4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.RBFClassifier" name="22">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-N</object>
            <object class="java.lang.String" name="1">2</object>
            <object class="java.lang.String" name="2">-R</object>
            <object class="java.lang.String" name="3">0.01</object>
            <object class="java.lang.String" name="4">-L</object>
            <object class="java.lang.String" name="5">1.0E-6</object>
            <object class="java.lang.String" name="6">-C</object>
            <object class="java.lang.String" name="7">2</object>
            <object class="java.lang.String" name="8">-P</object>
            <object class="java.lang.String" name="9">1</object>
            <object class="java.lang.String" name="10">-E</object>
            <object class="java.lang.String" name="11">1</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="23">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.RBFClassifier</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-N</object>
            <object class="java.lang.String" name="8">2</object>
            <object class="java.lang.String" name="9">-R</object>
            <object class="java.lang.String" name="10">0.01</object>
            <object class="java.lang.String" name="11">-L</object>
            <object class="java.lang.String" name="12">1.0E-6</object>