<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.bayes.NaiveBayes" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayes" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.bayes.NaiveBayes</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.AveragedNDependenceEstimators.A1DE" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.bayes.AveragedNDependenceEstimators.A1DE</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-F</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">1.0</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.AveragedNDependenceEstimators.A2DE" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.bayes.AveragedNDependenceEstimators.A2DE</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-F</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">1.0</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.BayesNet" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.TAN</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">BAYES</object>
            <object class="java.lang.String" name="6">-E</object>
            <object class="java.lang.String" name="7">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
            <object class="java.lang.String" name="8">--</object>
            <object class="java.lang.String" name="9">-A</object>
            <object class="java.lang.String" name="10">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="9">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.bayes.BayesNet</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-D</object>
            <object class="java.lang.String" name="8">-Q</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.net.search.local.TAN</object>
            <object class="java.lang.String" name="10">--</object>
            <object class="java.lang.String" name="11">-S</object>
            <object class="java.lang.String" name="12">BAYES</object>
            <object class="java.lang.String" name="13">-E</object>
            <object class="java.lang.String" name="14">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
            <object class="java.lang.String" name="15">--</object>
            <object class="java.lang.String" name="16">-A</object>
            <object class="java.lang.String" name="17">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.BayesNet" name="10">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.K2</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">BAYES</object>
            <object class="java.lang.String" name="8">-E</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
            <object class="java.lang.String" name="10">--</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="11">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.bayes.BayesNet</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-D</object>
            <object class="java.lang.String" name="8">-Q</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.net.search.local.K2</object>
            <object class="java.lang.String" name="10">--</object>
            <object class="java.lang.String" name="11">-P</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-S</object>
            <object class="java.lang.String" name="14">BAYES</object>
            <object class="java.lang.String" name="15">-E</object>
            <object class="java.lang.String" name="16">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
            <object class="java.lang.String" name="17">--</object>
            <object class="java.lang.String" name="18">-A</object>
            <object class="java.lang.String" name="19">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.NBTree" name="12">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="13">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.NBTree</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="14">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-8</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="15">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.Logistic</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-R</object>
            <object class="java.lang.String" name="8">1.0E-8</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">-1</object>
            <object class="java.lang.String" name="11">-num-decimal-places</object>
            <object class="java.lang.String" name="12">4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SimpleLogistic" name="16">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">500</object>
            <object class="java.lang.String" name="4">-H</object>
            <object class="java.lang.String" name="5">50</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="17">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.SimpleLogistic</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-I</object>
            <object class="java.lang.String" name="8">0</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">500</object>
            <object class="java.lang.String" name="11">-H</object>
            <object class="java.lang.String" name="12">50</object>
            <object class="java.lang.String" name="13">-W</object>
            <object class="java.lang.String" name="14">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.Stacking" name="18">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-X</object>
            <object class="java.lang.String" name="1">10</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.Logistic -R 1.0E-8 -M -1 -num-decimal-places 4</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-num-slots</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-B</object>
            <object class="java.lang.String" name="9">weka.classifiers.rules.ZeroR</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="19">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.meta.Stacking</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-X</object>
            <object class="java.lang.String" name="8">10</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">weka.classifiers.functions.Logistic -R 1.0E-8 -M -1 -num-decimal-places 4</object>
            <object class="java.lang.String" name="11">-S</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-num-slots</object>
            <object class="java.lang.String" name="14">1</object>
            <object class="java.lang.String" name="15">-B</object>
            <object class="java.lang.String" name="16">weka.classifiers.rules.ZeroR</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.Bagging" name="20">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-I</object>
            <object class="java.lang.String" name="7">10</object>
            <object class="java.lang.String" name="8">-W</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="21">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.meta.Bagging</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-P</object>
            <object class="java.lang.String" name="8">100</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-I</object>
            <object class="java.lang.String" name="14">10</object>
            <object class="java.lang.String" name="15">-W</object>
            <object class="java.lang.String" name="16">weka.classifiers.bayes.NaiveBayes</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_main_financial_metric.arff</object>
      <object class="java.io.File" name="1">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_fssu_main_financial_metric.arff</object>
      <object class="java.io.File" name="2">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_fssm_main_financial_metric.arff</object>
      <object class="java.io.File" name="3">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="4">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_fssu_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="5">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_fssm_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="6">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_proc_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="7">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_fssu_proc_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="8">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_fssm_proc_std_main_financial_metrics.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">3</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">5</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">final_raw+fssu+fssm_prob.arff</object>
      </object>