<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">0.25</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.RandomForest</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-P</object>
            <object class="java.lang.String" name="8">100</object>
            <object class="java.lang.String" name="9">-I</object>
            <object class="java.lang.String" name="10">100</object>
            <object class="java.lang.String" name="11">-num-slots</object>
            <object class="java.lang.String" name="12">1</object>
            <object class="java.lang.String" name="13">-K</object>
            <object class="java.lang.String" name="14">0</object>
            <object class="java.lang.String" name="15">-M</object>
            <object class="java.lang.String" name="16">1.0</object>
            <object class="java.lang.String" name="17">-V</object>
            <object class="java.lang.String" name="18">0.001</object>
            <object class="java.lang.String" name="19">-S</object>
            <object class="java.lang.String" name="20">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.rules.JRip</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-F</object>
            <object class="java.lang.String" name="8">3</object>
            <object class="java.lang.String" name="9">-N</object>
            <object class="java.lang.String" name="10">2.0</object>
            <object class="java.lang.String" name="11">-O</object>
            <object class="java.lang.String" name="12">2</object>
            <object class="java.lang.String" name="13">-S</object>
            <object class="java.lang.String" name="14">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.rules.OneR</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-B</object>
            <object class="java.lang.String" name="8">6</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.rules.DecisionTable</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-X</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">weka.attributeSelection.BestFirst -D 1 -N 5</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.lazy.IBk</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-K</object>
            <object class="java.lang.String" name="8">1</object>
            <object class="java.lang.String" name="9">-W</object>
            <object class="java.lang.String" name="10">0</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">weka.core.neighboursearch.LinearNNSearch -A &quot;weka.core.EuclideanDistance -R first-last&quot;</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.lazy.KStar</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-B</object>
            <object class="java.lang.String" name="8">40</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">a</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.RBFClassifier</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-N</object>
            <object class="java.lang.String" name="8">2</object>
            <object class="java.lang.String" name="9">-R</object>
            <object class="java.lang.String" name="10">0.01</object>
            <object class="java.lang.String" name="11">-L</object>
            <object class="java.lang.String" name="12">1.0E-6</object>
            <object class="java.lang.String" name="13">-C</object>
            <object class="java.lang.String" name="14">2</object>
            <object class="java.lang.String" name="15">-P</object>
            <object class="java.lang.String" name="16">1</object>
            <object class="java.lang.String" name="17">-E</object>
            <object class="java.lang.String" name="18">1</object>
            <object class="java.lang.String" name="19">-S</object>
            <object class="java.lang.String" name="20">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N 15</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.SMO</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">1.0</object>
            <object class="java.lang.String" name="9">-L</object>
            <object class="java.lang.String" name="10">0.001</object>
            <object class="java.lang.String" name="11">-P</object>
            <object class="java.lang.String" name="12">1.0E-12</object>
            <object class="java.lang.String" name="13">-N</object>
            <object class="java.lang.String" name="14">0</object>
            <object class="java.lang.String" name="15">-V</object>
            <object class="java.lang.String" name="16">-1</object>
            <object class="java.lang.String" name="17">-W</object>
            <object class="java.lang.String" name="18">1</object>
            <object class="java.lang.String" name="19">-K</object>
            <object class="java.lang.String" name="20">weka.classifiers.functions.supportVector.PolyKernel -E 1.0 -C 250007</object>
            <object class="java.lang.String" name="21">-calibrator</object>
            <object class="java.lang.String" name="22">weka.classifiers.functions.Logistic -R 1.0E-8 -M -1 -num-decimal-places 4</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_main_financial_metric.arff</object>
      <object class="java.io.File" name="1">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="2">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_proc_std_main_financial_metrics.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">3</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">5</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">final_fssu_non_prob.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/resutls/final_fssu_non_prob.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">false</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
