<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.bayes.BayesNet" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.K2</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">BAYES</object>
            <object class="java.lang.String" name="8">-E</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
            <object class="java.lang.String" name="10">--</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.BayesNet" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">BAYES</object>
            <object class="java.lang.String" name="8">-E</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
            <object class="java.lang.String" name="10">--</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.BayesNet" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.HillClimber</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">BAYES</object>
            <object class="java.lang.String" name="8">-E</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.net.estimate.BMAEstimator</object>
            <object class="java.lang.String" name="10">--</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.BayesNet" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.TAN</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-S</object>
            <object class="java.lang.String" name="5">BAYES</object>
            <object class="java.lang.String" name="6">-E</object>
            <object class="java.lang.String" name="7">weka.classifiers.bayes.net.estimate.SimpleEstimator</object>
            <object class="java.lang.String" name="8">--</object>
            <object class="java.lang.String" name="9">-A</object>
            <object class="java.lang.String" name="10">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.BayesNet" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.TabuSearch</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-L</object>
            <object class="java.lang.String" name="5">5</object>
            <object class="java.lang.String" name="6">-U</object>
            <object class="java.lang.String" name="7">10</object>
            <object class="java.lang.String" name="8">-P</object>
            <object class="java.lang.String" name="9">1</object>
            <object class="java.lang.String" name="10">-S</object>
            <object class="java.lang.String" name="11">BAYES</object>
            <object class="java.lang.String" name="12">-E</object>
            <object class="java.lang.String" name="13">weka.classifiers.bayes.net.estimate.BMAEstimator</object>
            <object class="java.lang.String" name="14">--</object>
            <object class="java.lang.String" name="15">-A</object>
            <object class="java.lang.String" name="16">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.BayesNet" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
            <object class="java.lang.String" name="1">-Q</object>
            <object class="java.lang.String" name="2">weka.classifiers.bayes.net.search.local.K2</object>
            <object class="java.lang.String" name="3">--</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">BAYES</object>
            <object class="java.lang.String" name="8">-E</object>
            <object class="java.lang.String" name="9">weka.classifiers.bayes.net.estimate.BMAEstimator</object>
            <object class="java.lang.String" name="10">--</object>
            <object class="java.lang.String" name="11">-A</object>
            <object class="java.lang.String" name="12">0.5</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayes" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayes" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="9">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="10">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-batch-size</object>
            <object class="java.lang.String" name="1">200</object>
            <object class="java.lang.String" name="2">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="11">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-batch-size</object>
            <object class="java.lang.String" name="1">500</object>
            <object class="java.lang.String" name="2">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="12">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-8</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="13">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-4</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="14">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">0.001</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SimpleLogistic" name="15">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-H</object>
            <object class="java.lang.String" name="5">50</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SimpleLogistic" name="16">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">500</object>
            <object class="java.lang.String" name="4">-H</object>
            <object class="java.lang.String" name="5">50</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SimpleLogistic" name="17">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-H</object>
            <object class="java.lang.String" name="5">50</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">0.0</object>
            <object class="java.lang.String" name="8">-batch-size</object>
            <object class="java.lang.String" name="9">1000</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.LDA" name="18">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">0.01</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.LDA" name="19">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">0.01</object>
            <object class="java.lang.String" name="2">-batch-size</object>
            <object class="java.lang.String" name="3">500</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.LDA" name="20">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.LDA" name="21">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-4</object>
            <object class="java.lang.String" name="2">-batch-size</object>
            <object class="java.lang.String" name="3">500</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.LDA" name="22">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-6</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.LDA" name="23">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-6</object>
            <object class="java.lang.String" name="2">-batch-size</object>
            <object class="java.lang.String" name="3">500</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.QDA" name="24">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.QDA" name="25">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-6</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.NBTree" name="26">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.bayes.AveragedNDependenceEstimators.A1DE" name="27">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.AveragedNDependenceEstimators.A2DE" name="28">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_num_a_main_financial_metrics.arff</object>
      <object class="java.io.File" name="1">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_num_a_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="2">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_num_a_proc_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="3">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_num_a_processed_std_bal_main_financial_metrics.arff</object>
      <object class="java.io.File" name="4">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_num_a_std_bal_main_finantial_metrics.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">3</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">result_prob.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/resutls/result_prob.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">false</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
