<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.bayes.NaiveBayes" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-D</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayes" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesSimple" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesSimple" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-batch-size</object>
            <object class="java.lang.String" name="1">200</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesSimple" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-batch-size</object>
            <object class="java.lang.String" name="1">500</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options"/>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-batch-size</object>
            <object class="java.lang.String" name="1">200</object>
            <object class="java.lang.String" name="2">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.bayes.NaiveBayesUpdateable" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-batch-size</object>
            <object class="java.lang.String" name="1">500</object>
            <object class="java.lang.String" name="2">-K</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="9">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-8</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="10">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">1.0E-4</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.Logistic" name="11">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-R</object>
            <object class="java.lang.String" name="1">0.001</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">-1</object>
            <object class="java.lang.String" name="4">-num-decimal-places</object>
            <object class="java.lang.String" name="5">4</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SimpleLogistic" name="12">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-H</object>
            <object class="java.lang.String" name="5">50</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SimpleLogistic" name="13">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">500</object>
            <object class="java.lang.String" name="4">-H</object>
            <object class="java.lang.String" name="5">50</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">0.0</object>
         </object>
      </object>
      <object class="weka.classifiers.functions.SimpleLogistic" name="14">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-H</object>
            <object class="java.lang.String" name="5">50</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">0.0</object>
            <object class="java.lang.String" name="8">-batch-size</object>
            <object class="java.lang.String" name="9">1000</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_main_financial_metrics.arff</object>
      <object class="java.io.File" name="1">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_processed_std_bal_main_financial_metrics.arff</object>
      <object class="java.io.File" name="2">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_std_bal_main_finantial_metrics.arff</object>
      <object class="java.io.File" name="3">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_std_main_financial_metrics.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">5</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">result_prob.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/resutls/result_prob.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">true</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
