<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.trees.J48" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.25</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.5</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.25</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.5</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">2</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.25</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">2</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.J48" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.5</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="9">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.supervised.attribute.Discretize -R first-last -precision 6</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.Id3</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="10">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="11">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">3</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="12">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">5</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="13">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-depth</object>
            <object class="java.lang.String" name="9">5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="14">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">3</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-depth</object>
            <object class="java.lang.String" name="9">5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="15">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">5</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-depth</object>
            <object class="java.lang.String" name="9">5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="16">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">0</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-depth</object>
            <object class="java.lang.String" name="9">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="17">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">3</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-depth</object>
            <object class="java.lang.String" name="9">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomTree" name="18">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-K</object>
            <object class="java.lang.String" name="1">5</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">1.0</object>
            <object class="java.lang.String" name="4">-V</object>
            <object class="java.lang.String" name="5">0.001</object>
            <object class="java.lang.String" name="6">-S</object>
            <object class="java.lang.String" name="7">1</object>
            <object class="java.lang.String" name="8">-depth</object>
            <object class="java.lang.String" name="9">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="19">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="20">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-batch-size</object>
            <object class="java.lang.String" name="15">200</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="21">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-batch-size</object>
            <object class="java.lang.String" name="15">500</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="22">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">5</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="23">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">5</object>
            <object class="java.lang.String" name="16">-batch-size</object>
            <object class="java.lang.String" name="17">200</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="24">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">5</object>
            <object class="java.lang.String" name="16">-batch-size</object>
            <object class="java.lang.String" name="17">200</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="25">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="26">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">10</object>
            <object class="java.lang.String" name="16">-batch-size</object>
            <object class="java.lang.String" name="17">200</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="27">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">10</object>
            <object class="java.lang.String" name="16">-batch-size</object>
            <object class="java.lang.String" name="17">500</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="28">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">20</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="29">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
            <object class="java.lang.String" name="14">-depth</object>
            <object class="java.lang.String" name="15">20</object>
            <object class="java.lang.String" name="16">-batch-size</object>
            <object class="java.lang.String" name="17">200</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="30">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>