<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <object class="weka.classifiers.trees.J48" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-C</object>
            <object class="java.lang.String" name="1">0.1</object>
            <object class="java.lang.String" name="2">-M</object>
            <object class="java.lang.String" name="3">10</object>
         </object>
      </object>
      <object class="weka.classifiers.trees.RandomForest" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">100</object>
            <object class="java.lang.String" name="4">-num-slots</object>
            <object class="java.lang.String" name="5">1</object>
            <object class="java.lang.String" name="6">-K</object>
            <object class="java.lang.String" name="7">0</object>
            <object class="java.lang.String" name="8">-M</object>
            <object class="java.lang.String" name="9">1.0</object>
            <object class="java.lang.String" name="10">-V</object>
            <object class="java.lang.String" name="11">0.001</object>
            <object class="java.lang.String" name="12">-S</object>
            <object class="java.lang.String" name="13">1</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">0.25</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.CfsSubsetEval -P 1 -E 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.BestFirst -D 1 -N 5</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">0.25</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.WrapperSubsetEval -B weka.classifiers.trees.J48 -F 5 -T 0.01 -R 1 -E DEFAULT -- -C 0.25 -M 2</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.BestFirst -D 1 -N 5</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">0.25</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.FilteredClassifier" name="5">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-F</object>
            <object class="java.lang.String" name="1">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 10.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 210.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-C</object>
            <object class="java.lang.String" name="8">0.25</object>
            <object class="java.lang.String" name="9">-M</object>
            <object class="java.lang.String" name="10">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="6">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.InfoGainAttributeEval</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.Ranker -T -1.7976931348623157E308 -N -1</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.meta.FilteredClassifier</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-F</object>
            <object class="java.lang.String" name="8">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 220.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 15.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-W</object>
            <object class="java.lang.String" name="12">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="13">--</object>
            <object class="java.lang.String" name="14">-C</object>
            <object class="java.lang.String" name="15">0.25</object>
            <object class="java.lang.String" name="16">-M</object>
            <object class="java.lang.String" name="17">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="7">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.CfsSubsetEval -P 1 -E 1</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.BestFirst -D 1 -N 5</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.meta.FilteredClassifier</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-F</object>
            <object class="java.lang.String" name="8">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 220.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 15.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-W</object>
            <object class="java.lang.String" name="12">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="13">--</object>
            <object class="java.lang.String" name="14">-C</object>
            <object class="java.lang.String" name="15">0.25</object>
            <object class="java.lang.String" name="16">-M</object>
            <object class="java.lang.String" name="17">2</object>
         </object>
      </object>
      <object class="weka.classifiers.meta.AttributeSelectedClassifier" name="8">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-E</object>
            <object class="java.lang.String" name="1">weka.attributeSelection.WrapperSubsetEval -B weka.classifiers.trees.J48 -F 5 -T 0.01 -R 1 -E DEFAULT -- -C 0.25 -M 2</object>
            <object class="java.lang.String" name="2">-S</object>
            <object class="java.lang.String" name="3">weka.attributeSelection.BestFirst -D 1 -N 5</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.meta.FilteredClassifier</object>
            <object class="java.lang.String" name="6">--</object>
            <object class="java.lang.String" name="7">-F</object>
            <object class="java.lang.String" name="8">weka.filters.MultiFilter -F &quot;weka.filters.supervised.instance.SMOTE -C 5 -K 5 -P 220.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 1 -K 5 -P 100.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 2 -K 5 -P 15.0 -S 1&quot; -F &quot;weka.filters.supervised.instance.SMOTE -C 4 -K 5 -P 30.0 -S 1&quot; -S 1</object>
            <object class="java.lang.String" name="9">-S</object>
            <object class="java.lang.String" name="10">1</object>
            <object class="java.lang.String" name="11">-W</object>
            <object class="java.lang.String" name="12">weka.classifiers.trees.J48</object>
            <object class="java.lang.String" name="13">--</object>
            <object class="java.lang.String" name="14">-C</object>
            <object class="java.lang.String" name="15">0.25</object>
            <object class="java.lang.String" name="16">-M</object>
            <object class="java.lang.String" name="17">2</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_main_financial_metric.arff</object>
      <object class="java.io.File" name="1">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="2">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_proc_std_main_financial_metrics.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">3</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">10</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">trees.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/resutls/trees.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">false</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
