<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE object
[
   <!ELEMENT object (#PCDATA|object)*>
   <!ATTLIST object name      CDATA #REQUIRED>
   <!ATTLIST object class     CDATA #REQUIRED>
   <!ATTLIST object primitive CDATA "no">
   <!ATTLIST object array     CDATA "no">   <!-- the dimensions of the array; no=0, yes=1 -->
   <!ATTLIST object null      CDATA "no">
   <!ATTLIST object version   CDATA "3.9.6">
]
>

<object class="weka.experiment.Experiment" name="__root__" version="3.9.6">
   <object array="yes" class="weka.classifiers.Classifier" name="propertyArray">
      <!-- 0️⃣ SimpleLogistic + LogitBoost -->
      <object class="weka.classifiers.meta.LogitBoost" name="0">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">50</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.functions.SimpleLogistic</object>
         </object>
      </object>

      <!-- 1️⃣ LMT + Bagging -->
      <object class="weka.classifiers.meta.Bagging" name="1">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-P</object>
            <object class="java.lang.String" name="1">100</object>
            <object class="java.lang.String" name="2">-I</object>
            <object class="java.lang.String" name="3">25</object>
            <object class="java.lang.String" name="4">-W</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.LMT</object>
         </object>
      </object>

      <!-- 2️⃣ RBFClassifier + CVParameterSelection -->
      <object class="weka.classifiers.meta.CVParameterSelection" name="2">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-X</object>
            <object class="java.lang.String" name="1">10</object>
            <object class="java.lang.String" name="2">-P</object>
            <object class="java.lang.String" name="3">G 0.1 10 3</object>
            <object class="java.lang.String" name="4">-P</object>
            <object class="java.lang.String" name="5">N 2 10 3</object>
            <object class="java.lang.String" name="6">-W</object>
            <object class="java.lang.String" name="7">weka.classifiers.functions.RBFClassifier</object>
         </object>
      </object>

      <!-- 3️⃣ SMO + AdaBoost -->
      <object class="weka.classifiers.meta.AdaBoostM1" name="3">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-I</object>
            <object class="java.lang.String" name="1">25</object>
            <object class="java.lang.String" name="2">-W</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.SMO</object>
         </object>
      </object>

      <!-- 4️⃣ Stacking (RBF + LMT + SMO → Logistic) -->
      <object class="weka.classifiers.meta.Stacking" name="4">
         <object class="boolean" name="debug" primitive="yes">false</object>
         <object array="yes" class="java.lang.String" name="options">
            <object class="java.lang.String" name="0">-M</object>
            <object class="java.lang.String" name="1">weka.classifiers.functions.Logistic</object>
            <object class="java.lang.String" name="2">-B</object>
            <object class="java.lang.String" name="3">weka.classifiers.functions.RBFClassifier</object>
            <object class="java.lang.String" name="4">-B</object>
            <object class="java.lang.String" name="5">weka.classifiers.trees.LMT</object>
            <object class="java.lang.String" name="6">-B</object>
            <object class="java.lang.String" name="7">weka.classifiers.functions.SMO</object>
         </object>
      </object>
   </object>
   <object class="javax.swing.DefaultListModel" name="datasets">
      <object class="java.io.File" name="0">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_main_financial_metric.arff</object>
      <object class="java.io.File" name="1">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_std_main_financial_metrics.arff</object>
      <object class="java.io.File" name="2">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/WEKA_training/train_a_proc_std_main_financial_metrics.arff</object>
   </object>
   <object class="int" name="runUpper" primitive="yes">3</object>
   <object class="weka.experiment.CrossValidationResultProducer" name="resultProducer">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-X</object>
         <object class="java.lang.String" name="1">5</object>
         <object class="java.lang.String" name="2">-O</object>
         <object class="java.lang.String" name="3">splitEvalutorOut.zip</object>
         <object class="java.lang.String" name="4">-W</object>
         <object class="java.lang.String" name="5">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="6">--</object>
         <object class="java.lang.String" name="7">-W</object>
         <object class="java.lang.String" name="8">weka.classifiers.rules.ZeroR</object>
         <object class="java.lang.String" name="9">-I</object>
         <object class="java.lang.String" name="10">0</object>
         <object class="java.lang.String" name="11">-C</object>
         <object class="java.lang.String" name="12">1</object>
         <object class="java.lang.String" name="13">--</object>
      </object>
   </object>
   <object class="boolean" name="usePropertyIterator" primitive="yes">true</object>
   <object array="yes" class="weka.experiment.PropertyNode" name="propertyPath">
      <object array="no" class="weka.experiment.PropertyNode" name="0" primitive="no">
         <object class="weka.experiment.ClassifierSplitEvaluator" name="value">
            <object array="yes" class="java.lang.String" name="options">
               <object class="java.lang.String" name="0">-W</object>
               <object class="java.lang.String" name="1">weka.classifiers.rules.ZeroR</object>
               <object class="java.lang.String" name="2">-I</object>
               <object class="java.lang.String" name="3">0</object>
               <object class="java.lang.String" name="4">-C</object>
               <object class="java.lang.String" name="5">1</object>
               <object class="java.lang.String" name="6">--</object>
            </object>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.CrossValidationResultProducer</object>
         <object class="java.lang.String" name="property">splitEvaluator</object>
      </object>
      <object array="no" class="weka.experiment.PropertyNode" name="1" primitive="no">
         <object class="weka.classifiers.rules.ZeroR" name="value">
            <object class="boolean" name="debug" primitive="yes">false</object>
            <object array="yes" class="java.lang.String" name="options"/>
         </object>
         <object class="java.lang.String" name="parentClass">weka.experiment.ClassifierSplitEvaluator</object>
         <object class="java.lang.String" name="property">classifier</object>
      </object>
   </object>
   <object class="java.lang.String" name="notes"/>
   <object class="weka.experiment.InstancesResultListener" name="resultListener">
      <object array="yes" class="java.lang.String" name="options">
         <object class="java.lang.String" name="0">-O</object>
         <object class="java.lang.String" name="1">wrap_non_prob.arff</object>
      </object>
      <object class="java.io.File" name="outputFile">C:/Users/SergioBeamonteGonzal/Documentos Locales/MASTER/Machine Learning/1-ML_Model/resutls/wrap_non_prob.arff</object>
   </object>
   <object class="boolean" name="advanceDataSetFirst" primitive="yes">false</object>
   <object class="int" name="runLower" primitive="yes">1</object>
   <object class="java.lang.Boolean" name="classFirst">false</object>
</object>
